### ISSUE TITLE
SSH vs HTTPS clone URLS

### ISSUE THREAD

**Issue by tofr** [stuy-softdev/fantastic-meme#2]
these teams need to rectify their linkages:

[submodule "7/phil_swifts_amazing_doors-cwalinaP-guptaS-hasanA-keriazisD"]
	path = 7/phil_swifts_amazing_doors-cwalinaP-guptaS-hasanA-keriazisD
	url = git@github.com:PeterCwalina/PSAD.git

[submodule "7/group-d-etat--ngR-onishiR-wongT-zhaoM"]
	path = 7/group-d-etat--ngR-onishiR-wongT-zhaoM
	url = git@github.com:rachel-ng/group-d-etat.git

[submodule "7/solid-learnination--chenJ-chowdhuryJ-johalP-rachlevskyM"]
	path = 7/solid-learnination--chenJ-chowdhuryJ-johalP-rachlevskyM
	url = git@github.com:jiayang/solid-learnination.git

**Comment by rachel-ng** [comment]
All submodules have survived the sinking of the SSH, success!
